// Generated by gencpp from file my_awesomme_code/WordCount.msg
// DO NOT EDIT!


#ifndef MY_AWESOMME_CODE_MESSAGE_WORDCOUNT_H
#define MY_AWESOMME_CODE_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <my_awesomme_code/WordCountRequest.h>
#include <my_awesomme_code/WordCountResponse.h>


namespace my_awesomme_code
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace my_awesomme_code


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_awesomme_code::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::my_awesomme_code::WordCount&) { return value(); }
};

template<>
struct DataType< ::my_awesomme_code::WordCount > {
  static const char* value()
  {
    return "my_awesomme_code/WordCount";
  }

  static const char* value(const ::my_awesomme_code::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::my_awesomme_code::WordCountRequest> should match 
// service_traits::MD5Sum< ::my_awesomme_code::WordCount > 
template<>
struct MD5Sum< ::my_awesomme_code::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_awesomme_code::WordCount >::value();
  }
  static const char* value(const ::my_awesomme_code::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_awesomme_code::WordCountRequest> should match 
// service_traits::DataType< ::my_awesomme_code::WordCount > 
template<>
struct DataType< ::my_awesomme_code::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::my_awesomme_code::WordCount >::value();
  }
  static const char* value(const ::my_awesomme_code::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_awesomme_code::WordCountResponse> should match 
// service_traits::MD5Sum< ::my_awesomme_code::WordCount > 
template<>
struct MD5Sum< ::my_awesomme_code::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_awesomme_code::WordCount >::value();
  }
  static const char* value(const ::my_awesomme_code::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_awesomme_code::WordCountResponse> should match 
// service_traits::DataType< ::my_awesomme_code::WordCount > 
template<>
struct DataType< ::my_awesomme_code::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::my_awesomme_code::WordCount >::value();
  }
  static const char* value(const ::my_awesomme_code::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_AWESOMME_CODE_MESSAGE_WORDCOUNT_H
