; Auto-generated. Do not edit!


(cl:in-package my_awesomme_code-msg)


;//! \htmlinclude TimerFeedback.msg.html

(cl:defclass <TimerFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TimerFeedback (<TimerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_awesomme_code-msg:<TimerFeedback> is deprecated: use my_awesomme_code-msg:TimerFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerFeedback>) ostream)
  "Serializes a message object of type '<TimerFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerFeedback>) istream)
  "Deserializes a message object of type '<TimerFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerFeedback>)))
  "Returns string type for a message object of type '<TimerFeedback>"
  "my_awesomme_code/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerFeedback)))
  "Returns string type for a message object of type 'TimerFeedback"
  "my_awesomme_code/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerFeedback>)))
  "Returns md5sum for a message object of type '<TimerFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerFeedback)))
  "Returns md5sum for a message object of type 'TimerFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerFeedback>)))
  "Returns full string definition for message of type '<TimerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerFeedback)))
  "Returns full string definition for message of type 'TimerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerFeedback
))
