; Auto-generated. Do not edit!


(cl:in-package my_awesomme_code-msg)


;//! \htmlinclude TimerResult.msg.html

(cl:defclass <TimerResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TimerResult (<TimerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_awesomme_code-msg:<TimerResult> is deprecated: use my_awesomme_code-msg:TimerResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerResult>) ostream)
  "Serializes a message object of type '<TimerResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerResult>) istream)
  "Deserializes a message object of type '<TimerResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerResult>)))
  "Returns string type for a message object of type '<TimerResult>"
  "my_awesomme_code/TimerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerResult)))
  "Returns string type for a message object of type 'TimerResult"
  "my_awesomme_code/TimerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerResult>)))
  "Returns md5sum for a message object of type '<TimerResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerResult)))
  "Returns md5sum for a message object of type 'TimerResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerResult>)))
  "Returns full string definition for message of type '<TimerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerResult)))
  "Returns full string definition for message of type 'TimerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerResult
))
